bday1 = input("Enter birthday day ")
bday2 = input("Enter birthday date ")
bday3 = input("Enter birthday time ")
bday4 = input("Enter birthday place: ")
bday5 = input("Enter birthday person: ")

print("\nBirthday Information:")
print("\nThe day")
print(bday1)
print("\nThe date")
print(bday2)
print("\nThe time")
print(bday3)
print("\nThe place")
print(bday4)
print("\nThe birthday person")
print(bday5)